from custom.functions import *  
from agents.antelope_agent import *
from agents.bush_agent import *
from agents.bird_agent import *
from agents.crocodile_agent import *
from agents.jungle_agent import *
from agents.lion_agent import *
from agents.snake_agent import *
from agents.water_agent import *